// <auto-generated />
namespace App.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CratePaymentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CratePaymentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202009091335166_CratePaymentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
