// <auto-generated />
namespace App.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ExamTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExamTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191650299_ExamTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
